# Generated by Django 4.1.7 on 2023-04-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Send_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=128, verbose_name='From')),
                ('to_name', models.CharField(max_length=128, verbose_name='To')),
                ('cc', models.CharField(max_length=128)),
                ('bcc', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=128)),
                ('email_template', models.CharField(max_length=128)),
                ('save_email_to_document_area', models.CharField(choices=[('site_documents', 'site_documents'), ('company_documents', 'company_documents')], default='', max_length=128)),
            ],
            options={
                'verbose_name': 'Send Email',
                'verbose_name_plural': 'Send Emails',
            },
        ),
    ]
