# Generated by Django 4.1.7 on 2023-04-13 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_my_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_email',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='emails.send_email'),
        ),
    ]
