# Generated by Django 4.1.7 on 2023-04-14 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_my_email_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='My_Email',
        ),
    ]
