# Generated by Django 4.1.7 on 2023-04-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_send_email_options'),
        ('emails', '0004_delete_my_email'),
    ]

    operations = [
    ]
