# Generated by Django 4.2.2 on 2023-08-14 10:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_contact_first_name', models.CharField(max_length=128)),
                ('primary_contact_last_name', models.CharField(max_length=128)),
                ('contact_title', models.CharField(choices=[('Sir', 'Sir'), ('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Dr', 'Dr')], max_length=128)),
                ('primary_contact_position', models.CharField(max_length=128)),
                ('telephone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('primary_contact_email', models.EmailField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
