# Generated by Django 4.2.2 on 2023-08-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contacts_company_contacts_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='primary_contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='primary_contact_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='primary_contact_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='primary_contact_position',
            new_name='position',
        ),
    ]
