# Generated by Django 4.2.2 on 2023-08-14 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0017_alter_billingaddress_site_alter_siteaddress_site'),
        ('contacts', '0003_rename_primary_contact_email_contacts_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='sites.site'),
        ),
    ]
