# Generated by Django 4.2.2 on 2023-08-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_company_contact_title_and_more'),
        ('sites', '0017_alter_billingaddress_site_alter_siteaddress_site'),
        ('contacts', '0004_alter_contacts_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='sites.site'),
        ),
    ]
