# Generated by Django 4.2.2 on 2023-08-16 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0017_alter_billingaddress_site_alter_siteaddress_site'),
        ('company', '0006_remove_company_contact_title_and_more'),
        ('contacts', '0005_alter_contacts_company_alter_contacts_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='company.company'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='site',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='sites.site'),
        ),
    ]
