# Generated by Django 4.2.2 on 2023-08-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contacts_company_alter_contacts_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='telephone_number',
            field=models.CharField(max_length=14),
        ),
    ]
