# Generated by Django 4.1.4 on 2022-12-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current_electricity_progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_step', models.CharField(max_length=128)),
                ('set_status_to', models.CharField(max_length=128)),
                ('priority', models.CharField(max_length=128)),
                ('completed', models.CharField(max_length=128)),
                ('completed_by', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Current_gas_progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_step', models.CharField(max_length=128)),
                ('set_status_to', models.CharField(max_length=128)),
                ('priority', models.CharField(max_length=128)),
                ('completed', models.CharField(max_length=128)),
                ('completed_by', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='New_electricity_progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_step', models.CharField(max_length=128)),
                ('set_status_to', models.CharField(max_length=128)),
                ('priority', models.CharField(max_length=128)),
                ('completed', models.CharField(max_length=128)),
                ('completed_by', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='New_gas_progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_step', models.CharField(max_length=128)),
                ('set_status_to', models.CharField(max_length=128)),
                ('priority', models.CharField(max_length=128)),
                ('completed', models.CharField(max_length=128)),
                ('completed_by', models.CharField(max_length=128)),
            ],
        ),
    ]
