# Generated by Django 4.1.5 on 2023-02-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="current_electricity_progress",
            options={
                "verbose_name": "Current electricity progress",
                "verbose_name_plural": "Current electricity progress",
            },
        ),
        migrations.AlterModelOptions(
            name="current_gas_progress",
            options={
                "verbose_name": "Current gas progress",
                "verbose_name_plural": "Current gas progress",
            },
        ),
        migrations.AlterModelOptions(
            name="new_electricity_progress",
            options={
                "verbose_name": "New electricity progress",
                "verbose_name_plural": "New electricity progress",
            },
        ),
        migrations.AlterModelOptions(
            name="new_gas_progress",
            options={
                "verbose_name": "New gas progress",
                "verbose_name_plural": "New gas progress",
            },
        ),
    ]
