# Generated by Django 4.1.7 on 2023-04-24 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0002_alter_current_electricity_progress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='current_gas_progress',
            options={'verbose_name': 'Current gas progress', 'verbose_name_plural': 'Current gas progresses'},
        ),
        migrations.RenameField(
            model_name='current_electricity_progress',
            old_name='progress_step',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='current_gas_progress',
            old_name='progress_step',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='new_electricity_progress',
            old_name='progress_step',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='new_gas_progress',
            old_name='progress_step',
            new_name='action',
        ),
        migrations.AddField(
            model_name='current_electricity_progress',
            name='callback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='current_gas_progress',
            name='callback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='new_electricity_progress',
            name='callback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='new_gas_progress',
            name='callback',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='current_electricity_progress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='current_electricity_progress',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='current_electricity_progress',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('CRITICAL', 'Critical')], default='LOW', max_length=128),
        ),
        migrations.AlterField(
            model_name='current_gas_progress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='current_gas_progress',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='current_gas_progress',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('CRITICAL', 'Critical')], default='LOW', max_length=128),
        ),
        migrations.AlterField(
            model_name='new_electricity_progress',
            name='completed',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='new_electricity_progress',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='new_electricity_progress',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('CRITICAL', 'Critical')], default='LOW', max_length=128),
        ),
        migrations.AlterField(
            model_name='new_gas_progress',
            name='completed',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='new_gas_progress',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='new_gas_progress',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('CRITICAL', 'Critical')], default='LOW', max_length=128),
        ),
    ]
