version: '3.7'
services:
  backend:
    build: .
    restart: on-failure
    # command: sh -c "gunicorn --config gunicorn_config.py /app/powercrm.wsgi:application"
    expose:
      - "8000"
    volumes:
      - ./:/app
      - staticfiles:/var/www/static/
      - /var/certbot/conf:/etc/letsencrypt/:ro
    env_file:
      - ./powercrm/settings/.env
    environment:
      - DJANGO_SETTINGS_MODULE=powercrm.settings.prod
      - STATIC_ROOT=/var/www/static/

    depends_on:
      - db
  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - staticfiles:/home/app/staticfiles/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - backend

  db:
    image: mysql:5.7
    restart: always
    container_name: p_db
    environment:
      MYSQL_DATABASE: 'powercrm_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  staticfiles:
  my-db:
    # certbot:
    #   image: certbot/certbot:latest
    #   volumes:
    #     - /var/certbot/conf:/etc/letsencrypt/:rw
    #     - /var/certbot/www/:/var/www/certbot/:rw
    #   depends_on:
    #     - nginx
