# Generated by Django 4.1.7 on 2023-04-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0011_site_loa_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='general_docs', verbose_name='Upload Document')),
                ('name', models.CharField(max_length=100, verbose_name='Document Name')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='')),
            ],
            options={
                'verbose_name': 'Site Document',
            },
        ),
        migrations.CreateModel(
            name='General_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='general_docs', verbose_name='Upload Document')),
                ('name', models.CharField(max_length=100, verbose_name='Document Name')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='')),
            ],
            options={
                'verbose_name': 'General Document',
            },
        ),
        migrations.CreateModel(
            name='Company_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='general_docs', verbose_name='Upload Document')),
                ('name', models.CharField(max_length=100, verbose_name='Document Name')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='')),
            ],
            options={
                'verbose_name': 'Company Document',
            },
        ),
    ]
