# Generated by Django 4.1.7 on 2023-04-11 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_site_loa_template'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_document',
            name='document',
            field=models.FileField(upload_to='company_docs', verbose_name='Upload Document'),
        ),
        migrations.AlterField(
            model_name='company_document',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AlterField(
            model_name='general_document',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AlterField(
            model_name='site_document',
            name='document',
            field=models.FileField(upload_to='site_docs', verbose_name='Upload Document'),
        ),
        migrations.AlterField(
            model_name='site_document',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
