# Generated by Django 4.1.7 on 2023-04-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_company_document_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general_document',
            name='site',
        ),
    ]
