# Generated by Django 4.1.7 on 2023-04-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_addressline1_company_and_more'),
        ('document', '0003_remove_general_document_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_document',
            name='site',
        ),
        migrations.AddField(
            model_name='company_document',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
