# Generated by Django 4.2.2 on 2023-08-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_user_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_credentials',
            name='state',
        ),
    ]
