# Generated by Django 4.2.2 on 2023-08-22 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0008_alter_user_credentials_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_credentials',
            name='access_token',
            field=models.CharField(default=2323232, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_credentials',
            name='refresh_token',
            field=models.CharField(default=232323, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_credentials',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
