# Generated by Django 4.2.2 on 2023-08-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_alter_user_credentials_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_credentials',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_credentials',
            name='selling_partner_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
