# Generated by Django 4.2.2 on 2023-08-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_alter_user_credentials_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_credentials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
