# Generated by Django 4.2.2 on 2023-08-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_user_credentials_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_credentials',
            name='market_place',
            field=models.CharField(choices=[('AMEN7PMS3EDWL', 'Belgium'), ('A1805IZSGTT6HS', 'Netherlands'), ('A1PA6795UKMFR9', 'Germany'), ('APJ6JRA9NG5V4', 'Italy'), ('A2NODRKZP88ZB9', 'Sweden'), ('A21TJRUUN4KGV', 'India'), ('A1F83G8C2ARO7P', 'United Kingdom'), ('ATVPDKIKX0DER', 'Sandbox')], default='ATVPDKIKX0DER', max_length=255, null=True),
        ),
    ]
