# Generated by Django 4.2.2 on 2023-08-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_user_credentials_market_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_credentials',
            old_name='market_place',
            new_name='market_place_id',
        ),
    ]
