# Generated by Django 4.2.4 on 2023-09-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_rename_market_place_user_credentials_market_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_document',
            name='document',
            field=models.FileField(upload_to='docs', verbose_name='Upload Document'),
        ),
        migrations.AlterField(
            model_name='general_document',
            name='document',
            field=models.FileField(upload_to='docs', verbose_name='Upload Document'),
        ),
        migrations.AlterField(
            model_name='site_document',
            name='document',
            field=models.FileField(upload_to='docs', verbose_name='Upload Document'),
        )
    ]
