# Generated by Django 4.2.4 on 2023-09-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_alter_company_document_document_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_credentials',
        ),
    ]
