# Generated by Django 4.1.7 on 2023-04-11 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gas_meter_detail',
            options={'verbose_name': 'Gas meter detail', 'verbose_name_plural': 'Gas meter details'},
        ),
        migrations.AlterField(
            model_name='meter_detail',
            name='electricity_meter_detail',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='supply.electricity_meter_detail', verbose_name='ELECTRICITY'),
        ),
        migrations.AlterField(
            model_name='meter_detail',
            name='gas_meter_detail',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='supply.gas_meter_detail', verbose_name='GAS'),
        ),
    ]
