# Generated by Django 4.1.7 on 2023-04-11 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_alter_gas_meter_detail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter_detail',
            name='electricity_meter_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supply.electricity_meter_detail', verbose_name='ELECTRICITY'),
        ),
        migrations.AlterField(
            model_name='meter_detail',
            name='gas_meter_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supply.gas_meter_detail', verbose_name='GAS'),
        ),
    ]
