# Generated by Django 4.1.7 on 2023-04-11 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_site_loa_template'),
        ('supply', '0003_alter_meter_detail_electricity_meter_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter_detail',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AlterField(
            model_name='meter_detail',
            name='electricity_meter_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply.electricity_meter_detail', verbose_name='ELECTRICITY'),
        ),
        migrations.AlterField(
            model_name='meter_detail',
            name='gas_meter_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply.gas_meter_detail', verbose_name='GAS'),
        ),
    ]
