# Generated by Django 4.1.7 on 2023-04-11 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_meter_detail_site_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricity_meter_detail',
            options={'verbose_name': 'Meter detail', 'verbose_name_plural': 'Meter detail'},
        ),
        migrations.AlterModelOptions(
            name='meter_detail',
            options={},
        ),
        migrations.RemoveField(
            model_name='meter_detail',
            name='electricity_meter_detail',
        ),
        migrations.RemoveField(
            model_name='meter_detail',
            name='gas_meter_detail',
        ),
        migrations.AddField(
            model_name='electricity_meter_detail',
            name='meter_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supply.meter_detail'),
        ),
        migrations.AddField(
            model_name='gas_meter_detail',
            name='meter_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supply.meter_detail'),
        ),
    ]
