# Generated by Django 4.1.7 on 2023-04-12 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0006_alter_electricity_meter_detail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity_meter_detail',
            name='meter_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_detail', to='supply.meter_detail'),
        ),
        migrations.AlterField(
            model_name='gas_meter_detail',
            name='meter_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='g_detail', to='supply.meter_detail'),
        ),
    ]
