# Generated by Django 4.1.7 on 2023-04-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0008_alter_electricity_meter_detail_meter_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gas_meter_detail',
            name='meter_detail',
        ),
        migrations.AddField(
            model_name='meter_detail',
            name='e_capacity',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meter_detail',
            name='e_green_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meter_detail',
            name='e_ley_meter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meter_detail',
            name='e_measurement_class',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meter_detail',
            name='e_meter_type',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meter_detail',
            name='e_mpan_bottomline',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meter_detail',
            name='e_mpan_topline',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meter_detail',
            name='e_related_meter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meter_detail',
            name='e_serial_number',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meter_detail',
            name='e_smart_meter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meter_detail',
            name='g_green_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meter_detail',
            name='g_igt_meter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meter_detail',
            name='g_mpr',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meter_detail',
            name='g_serial_number',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meter_detail',
            name='g_smart_meter',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Electricity_meter_detail',
        ),
        migrations.DeleteModel(
            name='Gas_meter_detail',
        ),
    ]
