# Generated by Django 4.1.7 on 2023-04-12 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_site_loa_template'),
        ('supply', '0010_alter_meter_detail_e_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter_detail',
            name='site',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
