# Generated by Django 4.1.7 on 2023-04-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0011_alter_meter_detail_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter_detail',
            name='e_green_deal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='meter_detail',
            name='e_ley_meter',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='meter_detail',
            name='e_related_meter',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='meter_detail',
            name='e_smart_meter',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='meter_detail',
            name='g_green_deal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='meter_detail',
            name='g_igt_meter',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='meter_detail',
            name='g_smart_meter',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
