# Generated by Django 4.1.7 on 2023-04-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_site_loa_template'),
        ('supply', '0013_remove_supply_detail_current_supplies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_supplies',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new_supplies',
            name='e_product',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='new_supplies',
            name='e_supplier',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='new_supplies',
            name='g_product',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='new_supplies',
            name='g_supplier',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='new_supplies',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
    ]
