# Generated by Django 4.1.7 on 2023-04-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0014_alter_current_supplies_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_supplies',
            name='e_green_deal',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='green Deal'),
        ),
    ]
