# Generated by Django 4.1.7 on 2023-04-13 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_site_loa_template'),
        ('supply', '0016_alter_new_supplies_e_igt_meter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity_current_supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(default='', max_length=128)),
                ('product', models.CharField(default='', max_length=128)),
                ('contract_type', models.CharField(choices=[('ElecAMR', 'ElecAMR'), ('ElecDomestic', 'ElecDomestic'), ('ElecHH', 'ElecHH'), ('ElecHHp272', 'ElecHHp272'), ('ElecNHH', 'ElecNHH'), ('GasAMR', 'GasAMR'), ('GasCommercial', 'GasCommercial'), (' GasDomestic', 'GasDomestic')], default='', max_length=128)),
                ('igt_meter', models.BooleanField(default=False)),
                ('green_deal', models.BooleanField(default=False)),
                ('won_date', models.DateField(null=True)),
                ('contract_start_date', models.DateField(null=True)),
                ('contract_end_date', models.DateField(null=True)),
                ('contract_length_months', models.CharField(default='', max_length=128)),
                ('contract_back_date', models.DateField(null=True)),
                ('supplier_reference', models.CharField(default='', max_length=128)),
                ('supplier_information1', models.CharField(default='', max_length=128)),
                ('supplier_information2', models.CharField(default='', max_length=128)),
                ('supplier_information3', models.CharField(default='', max_length=128)),
                ('agent', models.BooleanField(default=False)),
                ('customer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Electricity current supplies',
                'verbose_name_plural': 'Electricity current supplies',
            },
        ),
        migrations.CreateModel(
            name='Electricity_meter_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpan_topline', models.CharField(max_length=128)),
                ('mpan_bottomline', models.CharField(max_length=128)),
                ('meter_type', models.CharField(max_length=128)),
                ('serial_number', models.CharField(max_length=128)),
                ('capacity', models.CharField(max_length=128)),
                ('measurement_class', models.CharField(max_length=128)),
                ('smart_meter', models.BooleanField(default=False)),
                ('related_meter', models.BooleanField(default=False)),
                ('ley_meter', models.BooleanField(default=False)),
                ('green_deal', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Electricity meter detail',
                'verbose_name_plural': 'Electricity meter detail',
            },
        ),
        migrations.CreateModel(
            name='Electricity_new_supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(default='', max_length=128)),
                ('product', models.CharField(default='', max_length=128)),
                ('contract_type', models.CharField(choices=[('ElecAMR', 'ElecAMR'), ('ElecDomestic', 'ElecDomestic'), ('ElecHH', 'ElecHH'), ('ElecHHp272', 'ElecHHp272'), ('ElecNHH', 'ElecNHH'), ('GasAMR', 'GasAMR'), ('GasCommercial', 'GasCommercial'), (' GasDomestic', 'GasDomestic')], default='', max_length=128)),
                ('igt_meter', models.BooleanField(default=False)),
                ('green_deal', models.BooleanField(default=False)),
                ('won_date', models.DateField(null=True)),
                ('contract_start_date', models.DateField(null=True)),
                ('contract_end_date', models.DateField(null=True)),
                ('contract_length_months', models.CharField(default='', max_length=128)),
                ('contract_back_date', models.DateField(null=True)),
                ('supplier_reference', models.CharField(default='', max_length=128)),
                ('supplier_information1', models.CharField(default='', max_length=128)),
                ('supplier_information2', models.CharField(default='', max_length=128)),
                ('supplier_information3', models.CharField(default='', max_length=128)),
                ('agent', models.BooleanField(default=False)),
                ('customer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Electricity new supplies',
                'verbose_name_plural': 'Electricity new supplies',
            },
        ),
        migrations.CreateModel(
            name='Gas_current_supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=128)),
                ('product', models.CharField(max_length=128)),
                ('contract_type', models.CharField(choices=[('ElecAMR', 'ElecAMR'), ('ElecDomestic', 'ElecDomestic'), ('ElecHH', 'ElecHH'), ('ElecHHp272', 'ElecHHp272'), ('ElecNHH', 'ElecNHH'), ('GasAMR', 'GasAMR'), ('GasCommercial', 'GasCommercial'), (' GasDomestic', 'GasDomestic')], default='', max_length=128)),
                ('igt_meter', models.BooleanField(default=False)),
                ('green_deal', models.BooleanField(default=False)),
                ('won_date', models.DateField(null=True)),
                ('contract_start_date', models.DateField(null=True)),
                ('contract_end_date', models.DateField(null=True)),
                ('contract_length_months', models.CharField(max_length=128)),
                ('contract_back_date', models.DateField(null=True)),
                ('supplier_reference', models.CharField(max_length=128)),
                ('supplier_information1', models.CharField(max_length=128)),
                ('supplier_information2', models.CharField(max_length=128)),
                ('supplier_information3', models.CharField(max_length=128)),
                ('agent', models.BooleanField(default=False)),
                ('customer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Gas current supplies',
                'verbose_name_plural': 'Gas current supplies',
            },
        ),
        migrations.CreateModel(
            name='Gas_meter_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpr', models.CharField(max_length=128)),
                ('serial_number', models.CharField(max_length=128)),
                ('smart_meter', models.BooleanField(default=False)),
                ('igt_meter', models.BooleanField(default=False)),
                ('green_deal', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Gas meter detail',
                'verbose_name_plural': 'Gas meter detail',
            },
        ),
        migrations.CreateModel(
            name='Gas_new_supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=128)),
                ('product', models.CharField(max_length=128)),
                ('contract_type', models.CharField(choices=[('ElecAMR', 'ElecAMR'), ('ElecDomestic', 'ElecDomestic'), ('ElecHH', 'ElecHH'), ('ElecHHp272', 'ElecHHp272'), ('ElecNHH', 'ElecNHH'), ('GasAMR', 'GasAMR'), ('GasCommercial', 'GasCommercial'), (' GasDomestic', 'GasDomestic')], default='', max_length=128)),
                ('igt_meter', models.BooleanField(default=False)),
                ('green_deal', models.BooleanField(default=False)),
                ('won_date', models.DateField(null=True)),
                ('contract_start_date', models.DateField(null=True)),
                ('contract_end_date', models.DateField(null=True)),
                ('contract_length_months', models.CharField(max_length=128)),
                ('contract_back_date', models.DateField(null=True)),
                ('supplier_reference', models.CharField(max_length=128)),
                ('supplier_information1', models.CharField(max_length=128)),
                ('supplier_information2', models.CharField(max_length=128)),
                ('supplier_information3', models.CharField(max_length=128)),
                ('agent', models.BooleanField(default=False)),
                ('customer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Gas new supplies',
                'verbose_name_plural': 'Gas new supplies',
            },
        ),
        migrations.CreateModel(
            name='Old_New_supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_new_supplies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.electricity_new_supplies', verbose_name='ELECTRICITY')),
                ('gas_new_supplies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.gas_new_supplies', verbose_name='GAS')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'New supplies',
                'verbose_name_plural': 'New supplies',
            },
        ),
        migrations.CreateModel(
            name='Old_Meter_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_meter_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.electricity_meter_detail', verbose_name='ELECTRICITY')),
                ('gas_meter_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.gas_meter_detail', verbose_name='GAS')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Meter detail',
                'verbose_name_plural': 'Meter detail',
            },
        ),
        migrations.CreateModel(
            name='Old_Current_supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_current_supplies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.electricity_current_supplies', verbose_name='ELECTRICITY')),
                ('gas_current_supplies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.gas_current_supplies', verbose_name='GAS')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Current supplies',
                'verbose_name_plural': 'Current supplies',
            },
        ),
    ]
