# Generated by Django 4.1.7 on 2023-04-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0017_electricity_current_supplies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='old_meter_detail',
            name='electricity_meter_detail',
        ),
        migrations.RemoveField(
            model_name='old_meter_detail',
            name='gas_meter_detail',
        ),
        migrations.RemoveField(
            model_name='old_meter_detail',
            name='site',
        ),
        migrations.RemoveField(
            model_name='old_new_supplies',
            name='electricity_new_supplies',
        ),
        migrations.RemoveField(
            model_name='old_new_supplies',
            name='gas_new_supplies',
        ),
        migrations.RemoveField(
            model_name='old_new_supplies',
            name='site',
        ),
        migrations.DeleteModel(
            name='Old_Current_supplies',
        ),
        migrations.DeleteModel(
            name='Old_Meter_detail',
        ),
        migrations.DeleteModel(
            name='Old_New_supplies',
        ),
    ]
