# Generated by Django 4.1.7 on 2023-04-18 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0019_delete_electricity_current_supplies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.current_supplies')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.meter_detail')),
                ('new_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.new_supplies')),
            ],
        ),
    ]
