# Generated by Django 4.1.7 on 2023-04-18 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_site_loa_template'),
        ('supply', '0020_supplies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter_detail',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
