# Generated by Django 4.2.4 on 2023-11-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0023_alter_current_supplies_site_alter_meter_detail_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter_detail',
            name='e_voltage',
            field=models.FloatField(default=0, verbose_name='Voltage'),
            preserve_default=False,
        ),
    ]
