# Generated by Django 4.2.4 on 2023-11-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0024_meter_detail_e_voltage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_supplies',
            old_name='contract_length_months',
            new_name='g_contract_length_months',
        ),
        migrations.AddField(
            model_name='new_supplies',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
