# Generated by Django 4.2.4 on 2023-11-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0028_remove_current_supplies_e_green_deal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_supplies',
            name='decimal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
