# Generated by Django 4.2.4 on 2023-11-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0029_new_supplies_decimal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_supplies',
            name='decimal',
        ),
    ]
