# Generated by Django 4.2.4 on 2023-11-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('supply', '0030_remove_new_supplies_decimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stading_charge', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Standing Charge (pence/day)')),
                ('standing_charge_uplift', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Standing Charge Uplift (pence/day)')),
                ('unit_rate_uplift', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Unit Rate Uplift (pence/day)')),
                ('kva_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='kVA Rate (pence/day)')),
                ('feed_in_tariff', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Feed-in Tariff (FiT)')),
                ('annual_day_usage', models.IntegerField(blank=True, null=True, verbose_name='Annual Day Usage (kWh)')),
                ('day_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Day Rate (pence/kWh)')),
                ('night_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Night Rate (pence/kWh)')),
                ('annual_night_usage', models.IntegerField(blank=True, null=True, verbose_name='Annual Day Usage (kWh)')),
                ('evening_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Evening/Weekend Rate (pence/kWh)')),
                ('usage_type', models.CharField(choices=[('GAS', 'GAS'), ('ELECTRICITY', 'ELECTRICITY')], max_length=255)),
                ('annual_usage', models.IntegerField(blank=True, null=True, verbose_name='Annual Usage (kWh)')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
