# Generated by Django 4.2.4 on 2023-11-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('supply', '0031_usagerates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagerates',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'supply'), ('model', 'current_supplies')), models.Q(('app_label', 'supply'), ('model', 'new_supplies')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
