# Generated by Django 4.2.4 on 2023-11-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('supply', '0033_alter_usagerates_content_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usagerates',
            unique_together={('content_type', 'object_id')},
        ),
    ]
