# Generated by Django 4.2.4 on 2023-11-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0035_alter_usagerates_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerates',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='kVA Rate (pence/kWh)'),
        ),
    ]
