# Generated by Django 4.2.4 on 2023-11-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0036_usagerates_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerates',
            name='annual_evening_usage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Annual Evening/Weekend Usage (kWh)'),
        ),
    ]
