# Generated by Django 4.1.4 on 2022-12-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generate_Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(default='', max_length=128)),
                ('product', models.CharField(default='', max_length=128)),
                ('term', models.IntegerField()),
                ('day_rate', models.FloatField(verbose_name='Day Rate(pence/kwh)')),
                ('night_rate', models.FloatField(verbose_name='Night Rate(pence/kwh)')),
                ('standing_charge', models.FloatField(choices=[('perday', 'perday'), ('permonth', 'permonth'), ('peryear', 'peryear')], verbose_name='Standing Charge(pence)')),
                ('kva_charge', models.FloatField(choices=[('perday', 'perday'), ('permonth', 'permonth'), ('peryear', 'peryear')], verbose_name='Standing Charge(pence)')),
                ('additional_charge', models.FloatField(verbose_name='Additional Charge(£)')),
                ('extra_info', models.CharField(default='', max_length=128)),
                ('up_lift', models.FloatField(verbose_name='Up Lift')),
                ('rates_already_include_at_uplift', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quoting_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_custom_contract_end_date', models.BooleanField(default=False, verbose_name='Allow Custom Contract End Date')),
                ('include_feed_in_tariff_charges_in_prices', models.BooleanField(default=False, verbose_name='Include Feed-in Tariff(FiT) charges in prices')),
            ],
        ),
        migrations.CreateModel(
            name='Generate_Group_Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_detail', models.ManyToManyField(to='quoting.generate_quote')),
            ],
        ),
    ]
