# Generated by Django 4.1.4 on 2022-12-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generate_quote',
            name='kva_charge',
            field=models.FloatField(choices=[('perday', 'perday'), ('permonth', 'permonth')], verbose_name='Standing Charge(pence)'),
        ),
    ]
