# Generated by Django 4.1.4 on 2022-12-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0002_alter_generate_quote_kva_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generate_quote',
            name='kva_charge',
            field=models.CharField(choices=[('perday', 'perday'), ('permonth', 'permonth')], max_length=128, verbose_name='Standing Charge(pence)'),
        ),
        migrations.AlterField(
            model_name='generate_quote',
            name='standing_charge',
            field=models.CharField(choices=[('perday', 'perday'), ('permonth', 'permonth'), ('peryear', 'peryear')], max_length=128, verbose_name='Standing Charge(pence)'),
        ),
    ]
