# Generated by Django 4.1.5 on 2023-02-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quoting", "0004_alter_generate_quote_kva_charge_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generate_group_quote",
            options={
                "verbose_name": "Generate Group Quote",
                "verbose_name_plural": "Generate Group Quotes",
            },
        ),
        migrations.AlterModelOptions(
            name="generate_quote",
            options={
                "verbose_name": "Generate Quote",
                "verbose_name_plural": "Generate Quotes",
            },
        ),
        migrations.AlterModelOptions(
            name="quoting_settings",
            options={
                "verbose_name": "Quoting Settings",
                "verbose_name_plural": "Quoting Settings",
            },
        ),
    ]
