# Generated by Django 4.1.7 on 2023-04-17 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_site_loa_template'),
        ('quoting', '0005_alter_generate_group_quote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generate_quote',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
    ]
