# Generated by Django 4.1.7 on 2023-04-19 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0006_generate_quote_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoting_settings',
            options={'verbose_name': 'Quoting Setting', 'verbose_name_plural': 'Quoting Settings'},
        ),
    ]
