# Generated by Django 4.2.2 on 2023-08-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0007_alter_quoting_settings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='generate_group_quote',
            name='group_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generate_quote',
            name='kva_charge',
            field=models.FloatField(max_length=128, verbose_name='KVA Charge(pence)'),
        ),
    ]
