# Generated by Django 4.2.4 on 2023-09-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0008_generate_group_quote_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generate_quote',
            name='additional_charge',
            field=models.FloatField(blank=True, null=True, verbose_name='Additional Charge(£)'),
        ),
        migrations.AlterField(
            model_name='generate_quote',
            name='extra_info',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
