# Generated by Django 4.2.4 on 2023-09-20 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0009_alter_generate_quote_additional_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generate_quote',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
