# Generated by Django 4.2.4 on 2023-10-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0010_generate_quote_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generate_quote',
            name='day_rate',
            field=models.FloatField(null=True, verbose_name='Day Rate(pence/kwh)'),
        ),
        migrations.AlterField(
            model_name='generate_quote',
            name='kva_charge',
            field=models.FloatField(max_length=128, null=True, verbose_name='KVA Charge(pence)'),
        ),
        migrations.AlterField(
            model_name='generate_quote',
            name='night_rate',
            field=models.FloatField(null=True, verbose_name='Night Rate(pence/kwh)'),
        ),
        migrations.AlterField(
            model_name='generate_quote',
            name='standing_charge',
            field=models.FloatField(max_length=128, null=True, verbose_name='Standing Charge(pence)'),
        ),
        migrations.AlterField(
            model_name='generate_quote',
            name='term',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='generate_quote',
            name='up_lift',
            field=models.FloatField(null=True, verbose_name='Up Lift'),
        ),
    ]
