# Generated by Django 4.2.2 on 2023-08-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0017_alter_billingaddress_site_alter_siteaddress_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, null=True)),
                ('group_type', models.CharField(choices=[('BASIC', 'Basic Group'), ('MULTI', 'Multi Site Group')], max_length=50)),
                ('sites', models.ManyToManyField(to='sites.site')),
            ],
        ),
    ]
