# Generated by Django 4.2.4 on 2023-10-17 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_company_parent_company'),
        ('sites', '0019_remove_site_parent_company'),
        ('multisite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisite',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AlterField(
            model_name='multisite',
            name='sites',
            field=models.ManyToManyField(blank=True, to='sites.site'),
        ),
    ]
