# Generated by Django 4.1.7 on 2023-04-14 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_site_loa_template'),
        ('notes', '0003_alter_note_select_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='select_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Selected Site'),
        ),
    ]
