# Generated by Django 4.1.7 on 2023-04-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_alter_company_reminder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_reminder',
            name='reminder_type',
            field=models.CharField(choices=[('Callback', 'Callback'), ('Quotecallback', 'Quote callback'), ('Fsocallback', 'Fsocallback'), ('Renewalcallback', 'Renewal callback'), ('Other', 'Other')], max_length=128),
        ),
    ]
