# Generated by Django 4.1.7 on 2023-04-14 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_site_loa_template'),
        ('company', '0005_company_addressline1_company_and_more'),
        ('reminder', '0003_alter_general_reminder_reminder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_reminder',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Select Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site_reminder',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Select Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company_reminder',
            name='reminder_type',
            field=models.CharField(choices=[('Callback', 'Callback'), ('Quotecallback', 'Quote callback'), ('Fsocallback', 'Fsocallback'), ('Renewalcallback', 'Renewal callback'), ('Other', 'Other')], max_length=128),
        ),
        migrations.AlterField(
            model_name='site_reminder',
            name='reminder_type',
            field=models.CharField(choices=[('Callback', 'Callback'), ('Quotecallback', 'Quote callback'), ('Fsocallback', 'Fsocallback'), ('Renewalcallback', 'Renewal callback'), ('Other', 'Other')], max_length=128),
        ),
    ]
