# Generated by Django 4.1.7 on 2023-04-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_company_reminder_company_site_reminder_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site_reminder',
            old_name='company',
            new_name='site',
        ),
    ]
