# Generated by Django 4.1.7 on 2023-04-14 15:20

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0006_alter_company_reminder_alert_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_reminder',
            name='alert',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 15, 20, 16, 92244)),
        ),
        migrations.AlterField(
            model_name='company_reminder',
            name='alert_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='company_reminder',
            name='alert_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='general_reminder',
            name='alert_date',
            field=models.DateField(default=datetime.date(2023, 4, 14)),
        ),
        migrations.AlterField(
            model_name='general_reminder',
            name='alert_time',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AlterField(
            model_name='site_reminder',
            name='alert_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='site_reminder',
            name='alert_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
