# Generated by Django 4.1.7 on 2023-04-14 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0007_general_reminder_alert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general_reminder',
            name='alert_date',
        ),
        migrations.RemoveField(
            model_name='general_reminder',
            name='alert_time',
        ),
        migrations.AlterField(
            model_name='general_reminder',
            name='alert',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 15, 21, 35, 543932), verbose_name='Alert Date and Time '),
        ),
    ]
