# Generated by Django 4.1.7 on 2023-04-14 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0008_remove_general_reminder_alert_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_reminder',
            name='alert_date',
        ),
        migrations.RemoveField(
            model_name='company_reminder',
            name='alert_time',
        ),
        migrations.RemoveField(
            model_name='site_reminder',
            name='alert_date',
        ),
        migrations.RemoveField(
            model_name='site_reminder',
            name='alert_time',
        ),
        migrations.AddField(
            model_name='company_reminder',
            name='alert',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 15, 22, 41, 252505), verbose_name='Alert Date and Time '),
        ),
        migrations.AddField(
            model_name='site_reminder',
            name='alert',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 15, 22, 41, 252505), verbose_name='Alert Date and Time '),
        ),
        migrations.AlterField(
            model_name='general_reminder',
            name='alert',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 15, 22, 41, 246974), verbose_name='Alert Date and Time '),
        ),
    ]
