# Generated by Django 4.1.7 on 2023-04-07 10:21

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Business type',
                'verbose_name_plural': 'Business type',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ABC Limited', max_length=100, verbose_name='Name of the Company')),
                ('postcode', models.CharField(max_length=128)),
                ('number_of_employees', models.PositiveIntegerField()),
                ('registration_no', models.CharField(max_length=128)),
                ('estimated_turnover', models.IntegerField()),
                ('is_macro_business', models.BooleanField(default=False)),
                ('account_name', models.CharField(max_length=128)),
                ('bank_name', models.CharField(max_length=128)),
                ('account_no', models.CharField(max_length=128)),
                ('shortcode', models.CharField(max_length=128)),
                ('primary_contact_first_name', models.CharField(max_length=128)),
                ('primary_contact_last_name', models.CharField(max_length=128)),
                ('contact_title', models.CharField(max_length=128)),
                ('primary_contact_position', models.CharField(max_length=128)),
                ('telephone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('primary_contact_email', models.EmailField(max_length=128)),
                ('partner_name', models.CharField(max_length=128)),
                ('home_post_code', models.CharField(max_length=128)),
                ('partner_dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=128)),
                ('time_at_address_years', models.PositiveIntegerField(verbose_name='Time At Address(years)')),
                ('time_at_address_months', models.PositiveIntegerField(verbose_name='Time At Address(months)')),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.business_type')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
