# Generated by Django 4.1.7 on 2023-04-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_address_alter_company_contact_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='time_at_address_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Time At Address(months)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='time_at_address_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Time At Address(years)'),
        ),
    ]
