# Generated by Django 4.1.7 on 2023-04-10 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_time_at_address_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='addressline1_company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address Line 1 '),
        ),
        migrations.AddField(
            model_name='company',
            name='addressline2_company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address Line 2 '),
        ),
        migrations.AddField(
            model_name='company',
            name='addressline3_company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address Line 3 '),
        ),
        migrations.AddField(
            model_name='company',
            name='country_of_company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='credit_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Credit Score'),
        ),
        migrations.AddField(
            model_name='company',
            name='sic_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SIC Code '),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.business_type', verbose_name='Company Type'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_macro_business',
            field=models.BooleanField(default=False, verbose_name='Is Micro Business?'),
        ),
        migrations.AlterField(
            model_name='company',
            name='postcode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Postcode'),
        ),
    ]
