# Generated by Django 4.2.2 on 2023-08-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_company_contact_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='credit_score',
        ),
    ]
