# Generated by Django 4.2.2 on 2023-08-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_company_parent_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='parent_company',
            field=models.CharField(blank=True, help_text='Optional', max_length=128, null=True),
        ),
    ]
