# Generated by Django 4.1.7 on 2023-04-07 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, default='', max_length=128, unique=True)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Site_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_company', models.CharField(blank=True, max_length=128, null=True)),
                ('site_name', models.CharField(max_length=128)),
                ('type_of_owner', models.CharField(max_length=128)),
                ('owner_name', models.CharField(max_length=128)),
                ('current_gas_and_electricity_supplier_details', models.CharField(max_length=128)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Sitedetail', to='sites.site')),
            ],
            options={
                'verbose_name': 'Site Detail',
                'verbose_name_plural': 'Site Details',
            },
        ),
        migrations.CreateModel(
            name='Site_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=128)),
                ('addressline1', models.CharField(max_length=128)),
                ('addressline2', models.CharField(blank=True, max_length=128, null=True)),
                ('addressline3', models.CharField(blank=True, max_length=128, null=True)),
                ('addressline4', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(max_length=128)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Siteaddress', to='sites.site')),
            ],
            options={
                'verbose_name': 'Site address',
                'verbose_name_plural': 'Site addresses',
            },
        ),
        migrations.CreateModel(
            name='Our_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_reference', models.CharField(max_length=128)),
                ('lead_source', models.CharField(max_length=128)),
                ('notes', models.CharField(max_length=128)),
                ('lead_type', models.CharField(choices=[('GAS', 'GAS'), ('ELECTRICITY', 'ELECTRICITY')], default='', max_length=128)),
                ('bill_to_sent', models.BooleanField(default=False)),
                ('welcome_letter_send', models.BooleanField(default=False)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ourdetails', to='sites.site')),
                ('support_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Our Detail',
                'verbose_name_plural': 'Our Details',
            },
        ),
        migrations.CreateModel(
            name='Letter_of_authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_email', models.EmailField(max_length=128)),
                ('loa_header_to_use', models.CharField(max_length=128)),
                ('loa_template', models.CharField(max_length=128)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loa', to='sites.site')),
            ],
            options={
                'verbose_name': 'Letter of Authority',
                'verbose_name_plural': 'Letter of Authority',
            },
        ),
        migrations.CreateModel(
            name='Billing_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=128)),
                ('addressline1', models.CharField(max_length=128)),
                ('addressline2', models.CharField(blank=True, max_length=128, null=True)),
                ('addressline3', models.CharField(blank=True, max_length=128, null=True)),
                ('addressline4', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(max_length=128)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billingaddress', to='sites.site')),
            ],
            options={
                'verbose_name': 'Billing address',
                'verbose_name_plural': 'Billing addresses',
            },
        ),
    ]
