# Generated by Django 4.1.7 on 2023-04-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_rename_lead_typee_site_lead_typ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='addressline1',
            new_name='addressline1_billing',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='country',
            new_name='addressline1_site',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='addressline2',
            new_name='addressline2_billing',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='addressline3',
            new_name='addressline2_site',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='addressline4',
            new_name='addressline3_billing',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='postcode',
            new_name='country_billing',
        ),
        migrations.RemoveField(
            model_name='site',
            name='lead_typ',
        ),
        migrations.AddField(
            model_name='site',
            name='addressline3_site',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='addressline4_billing',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='addressline4_site',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='country_site',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='lead_type',
            field=models.CharField(choices=[('GAS', 'GAS'), ('ELECTRICITY', 'ELECTRICITY')], default='GAS', max_length=128),
        ),
        migrations.AddField(
            model_name='site',
            name='postcode_billing',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='postcode_site',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
