# Generated by Django 4.1.7 on 2023-04-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_site_change_of_tenancy_site_customer_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='addressline1_billing',
            field=models.CharField(blank=True, max_length=128, verbose_name='addressline 1'),
        ),
        migrations.AlterField(
            model_name='site',
            name='addressline1_site',
            field=models.CharField(blank=True, max_length=128, verbose_name='address line 1'),
        ),
        migrations.AlterField(
            model_name='site',
            name='agent_email',
            field=models.EmailField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='site',
            name='change_of_tenancy',
            field=models.BooleanField(default=False, verbose_name='CoT'),
        ),
        migrations.AlterField(
            model_name='site',
            name='country_billing',
            field=models.CharField(blank=True, max_length=128, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='site',
            name='country_site',
            field=models.CharField(blank=True, max_length=128, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='site',
            name='lead_type',
            field=models.CharField(blank=True, choices=[('GAS', 'GAS'), ('ELECTRICITY', 'ELECTRICITY')], default='GAS', max_length=128),
        ),
        migrations.AlterField(
            model_name='site',
            name='loa_header_to_use',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='site',
            name='loa_template',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='site',
            name='postcode_billing',
            field=models.CharField(blank=True, max_length=128, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='site',
            name='postcode_site',
            field=models.CharField(blank=True, max_length=128, verbose_name='Postcode'),
        ),
    ]
