# Generated by Django 4.1.7 on 2023-04-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_alter_site_addressline1_billing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loa_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Template')),
                ('template', models.FileField(upload_to='LOA_templates/')),
            ],
            options={
                'verbose_name': 'LOA Template',
                'verbose_name_plural': 'LOA Templates',
            },
        ),
        migrations.AlterField(
            model_name='site',
            name='loa_header_to_use',
            field=models.CharField(blank=True, choices=[('1', 'Site Name'), ('2', 'Company Name')], max_length=128, verbose_name='LOA Header to Use'),
        ),
    ]
