# Generated by Django 4.1.7 on 2023-04-10 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_loa_template_alter_site_loa_header_to_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='loa_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.loa_template', verbose_name='LOA Template'),
        ),
    ]
