# Generated by Django 4.1.7 on 2023-04-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_alter_site_loa_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='loa_template',
            field=models.CharField(blank=True, default=22, max_length=128),
            preserve_default=False,
        ),
    ]
