# Generated by Django 4.1.7 on 2023-04-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_alter_site_loa_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='loa_template',
        ),
    ]
