# Generated by Django 4.1.7 on 2023-04-10 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_remove_site_loa_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='loa_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.loa_template', verbose_name='LOA Template'),
        ),
    ]
