# Generated by Django 4.1.7 on 2023-04-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_site_loa_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='bill_to_sent',
            field=models.BooleanField(default=False, verbose_name='Bill to Sent'),
        ),
    ]
