# Generated by Django 4.2.2 on 2023-06-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0014_site_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='addressline1_billing',
        ),
        migrations.RemoveField(
            model_name='site',
            name='addressline1_site',
        ),
        migrations.RemoveField(
            model_name='site',
            name='addressline2_billing',
        ),
        migrations.RemoveField(
            model_name='site',
            name='addressline2_site',
        ),
        migrations.RemoveField(
            model_name='site',
            name='addressline3_billing',
        ),
        migrations.RemoveField(
            model_name='site',
            name='addressline3_site',
        ),
        migrations.RemoveField(
            model_name='site',
            name='addressline4_billing',
        ),
        migrations.RemoveField(
            model_name='site',
            name='addressline4_site',
        ),
        migrations.RemoveField(
            model_name='site',
            name='country_billing',
        ),
        migrations.RemoveField(
            model_name='site',
            name='country_site',
        ),
        migrations.RemoveField(
            model_name='site',
            name='postcode_billing',
        ),
        migrations.RemoveField(
            model_name='site',
            name='postcode_site',
        ),
        migrations.CreateModel(
            name='SiteAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressline1', models.CharField(blank=True, max_length=128, verbose_name='address line 1')),
                ('addressline2', models.CharField(blank=True, max_length=128, null=True, verbose_name='address line 2')),
                ('addressline3', models.CharField(blank=True, max_length=128, null=True, verbose_name='address line 3')),
                ('addressline4', models.CharField(blank=True, max_length=128, null=True, verbose_name='address line 4')),
                ('country', models.CharField(blank=True, max_length=128, verbose_name='Country')),
                ('postcode_site', models.CharField(blank=True, max_length=128, verbose_name='Postcode')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Site')),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressline1', models.CharField(blank=True, max_length=128, verbose_name='address line 1')),
                ('addressline2', models.CharField(blank=True, max_length=128, null=True, verbose_name='address line 2')),
                ('addressline3', models.CharField(blank=True, max_length=128, null=True, verbose_name='address line 3')),
                ('addressline4', models.CharField(blank=True, max_length=128, null=True, verbose_name='address line 4')),
                ('country', models.CharField(blank=True, max_length=128, verbose_name='Country')),
                ('postcode_site', models.CharField(blank=True, max_length=128, verbose_name='Postcode')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Site')),
            ],
        ),
    ]
