# Generated by Django 4.2.2 on 2023-06-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_remove_site_addressline1_billing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='postcode_site',
        ),
        migrations.RemoveField(
            model_name='siteaddress',
            name='postcode_site',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='postcode',
            field=models.CharField(default=1111, max_length=128, verbose_name='Postcode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteaddress',
            name='postcode',
            field=models.CharField(default=1111, max_length=128, verbose_name='Postcode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='addressline1',
            field=models.CharField(max_length=128, verbose_name='address line 1'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.CharField(max_length=128, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='siteaddress',
            name='addressline1',
            field=models.CharField(max_length=128, verbose_name='address line 1'),
        ),
        migrations.AlterField(
            model_name='siteaddress',
            name='country',
            field=models.CharField(max_length=128, verbose_name='Country'),
        ),
    ]
