# Generated by Django 4.2.2 on 2023-08-14 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0016_remove_billingaddress_postcode_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='sites.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='siteaddress',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_address', to='sites.site', verbose_name='Site'),
        ),
    ]
