# Generated by Django 4.2.2 on 2023-08-25 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_company_account_name_alter_company_account_no_and_more'),
        ('sites', '0017_alter_billingaddress_site_alter_siteaddress_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='current_gas_and_electricity_supplier_details',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='parent_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.company', verbose_name='Parent Company (Optional)'),
        ),
        migrations.AlterField(
            model_name='site',
            name='type_of_owner',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
